---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: unifi
  name: unifi-controller-configmap
  labels:
    app: unifi-controller
    app.kubernetes.io/app: unifi-controller
    app.kubernetes.io/project: unifi
data:
  system.properties.default: |+
    ## system.properties
    ##

    # Logging configuration
    debug.device=info
    debug.mgmt=info
    debug.sdn=info
    debug.system=info

    # Log everything to Standard Output
    unifi.logStdout=true

    is_configured_and_restarted=true
    is_default=false

    # Read database configuration from environment
    unifi.config.readEnv=true

    reporter-uuid=<YOUR_REPORTER_UUID>
    uuid=<YOUR_UUID>
